### ISSUE TITLE
createRenderManager throws bad_alloc exception

### ISSUE THREAD

**Issue by rhegner** [sensics/OSVR-RenderManager#106]
I'm trying to build the _RenderManagerD3DPresentSideBySideExample.cpp_ myself so that I have a starting point for my own project. 

Problem is, the call to `osvr::renderkit::createRenderManager` in line 195 throws the following exception:

`Unhandled exception at 0x74AEC54F in RenderManagerTest.exe: Microsoft C++ exception: std::bad_alloc at memory location 0x002FE678.`

I'm building with Visual Studio 2015 (v140) and I noticed that the the OSVR libraries were probably built with toolset v120. So my first guess was that the problem could be due to different heaps/runtimes across the DLL boundary. So I changed the toolset of my test application to v120, but it still throws the exception.

The exception is also thrown when I change the render library to `OpenGL`.

What could be the problem? Or how could I investigate it further?

**Comment by russell-taylor** [comment]
I do my testing on VS2013, and that is what I deploy the RenderManager installers for.  I think that this is also what the OSVR builds use, so you might try that.  I have in the past built both the OSVR libraries and RenderManager on VS 2015 and that worked.

If you can get VS2013 and try it, that is probably the safest bet.

If you can catch a stack trace in the debugger (you'll need to build JsonCPP in Debug mode to link against it in Debug mode), I'd love to know where the crash is so we can fix it.  Otherwise, I'll try compiling RenderManager with VS2015 and see if I can reproduce it.

Please report whether VS2013 fixes it or not.

**Comment by rhegner** [comment]
I just realized that it works when I build my sample application in Release configuration. Interestingly it doesn't make a difference whether I build my sample application with the current v140 toolset or with the v120 toolset (which is the VS2013 toolset).

It is still my impression that the problem comes from the fact that different C++ runtimes are used in the OSVR DLLs and in my application.

My experience with shared libraries under Windows is this: When linking them statically it is absolutely crucial that the same settings are used for building the application and for building the static library (same toolset, same debug/release configuration, same threading settings, ...). But we are linking the OSVR DLLs dynamically and for this case the rules are much less strict. In fact it _should_ be perfectly possible to build the OSVR DLLs and the application with different toolsets and therefore targeting different C++ runtimes. But for this to work one must make sure that the same runtime is used for deleting/freeing objects/memory as was used for creating/allocating it. I.e. objects created from within the DLL must be deleted from within the DLL and vice versa. This can become tricky when passing smart pointers or things like std::string across the DLL boundary. My experience is that it is best to have a pure C-style DLL interface (with functions exposed to delete objects created from within the DLL) and then maybe have a (header only) C++ wrapper around it.

To me the bad_alloc problem described above indicates that there could possibly be some room for improvement in the DLL interface of the RenderManager.

**Comment by rhegner** [comment]
As long as this issue exists I cannot build my application in Debug configuration, which makes it a bit of a pain to develop.

Unfortunately the OSVR SDK does not seem to include debug builds of its libraries. It would be great if you could add the debug build of the render manager to the SDK (at least for now, until the DLL interfacing problem is fixed).

**Comment by russell-taylor** [comment]
There is a C API for RenderManager that should behave the way you hope -- no problems linking debug to release and so forth across the DLL boundary.  It is the one to use for safety.

I'll ask the team to start building debug libraries in the installers as well as release -- that's a great idea!

**Comment by tobi-tobsen** [comment]
Just a heads up: I can build fine against the debug libraries, however during runtime I am also receiving a `std::bad_alloc` exception. Toggling back to Release compilation works.

**Comment by russell-taylor** [comment]
Thanks for the report.  Can you tell me what configuration you're running under -- DirectMode or not?  Which HMD?  Does it happen on one of the example programs (which one)?

**Comment by russell-taylor** [comment]
Debug works without crashing with Visual Studio 2015 latest patches on Windows 10 with an nVidia GTX 1080 driver version 382.53 using an HDK 2.0 for tracking but displaying on an undistorted extended-mode window on the screen.

**Comment by russell-taylor** [comment]
It also runs (though without tracking) for the HDK 2.0 in DirectMode.  It does not crash in the create code.

At this point, we'll need to know which configuration it crashes in so that we can reproduce it.

**Comment by russell-taylor** [comment]
Closed as not reproducible
