### ISSUE TITLE
RenderKitGraphicsTransformsC.h fails to compile in C

### ISSUE THREAD

**Issue by godbyk** [sensics/OSVR-RenderManager#113]
The `RenderKitGraphicsTransformsC.h` header can't be used with a straight C compiler:

 * Replace `extern "C" {`...`}` with `OSVR_EXTERN_C_BEGIN`...`OSVR_EXTERN_C_END`.
 * Return `OSVR_ReturnCode` instead of `bool` (`true` →`OSVR_RETURN_SUCCESS` and `false`→`OSVR_RETURN_FAILURE`).
 * Remove `#include <memory>`.
 * Update related C++ versions of those functions (or provide C wrappers).

**Comment by russell-taylor** [comment]
Sorry about that.  Just merged a pull request into Master that puts these where they should have been in the first place.
