### ISSUE TITLE
OSVR 1.4 / 2.0 Lens Distortion Question

### ISSUE THREAD

**Issue by Proxishh** [sensics/OSVR-RenderManager#118]
EDIT: I clicked the wrong link and believe I have posted in the wrong Github, my apologies.

Hey guys, still a little new to Github, so my apologies if this isn't the right place to ask this question.

With the lens distortion correction you guys are going to build into the next OSVR/SteamVR Driver, won't you need to create a separate build without lens distortion from here on out, since the 2.0 is going to have the same aspect ratio as the Vive?

Or is it the optics that are being corrected for in the next big release, and not the aspect ratio?

**Comment by godbyk** [comment]
The distortion correction primarily corrects for lens distortion.

In any case, RenderManager will provide the proper distortion correction function required for the HDK 2.0 when it's released, so SteamVR-OSVR won't need to be altered. You will just need to use the proper configuration file with OSVR to ensure the right parameters are used.
