### ISSUE TITLE
Missing header files in install directory

### ISSUE THREAD

**Issue by DuFF14** [sensics/OSVR-RenderManager#122]
OSVR-Unity-Rendering plugin was failing to build for me. Have to copy **Float2.h** and **UnstructuredMeshInterpolator.h** from RM source to its install directory C:\Program Files\osvrRenderManager\include\osvr\RenderKit to fix it.

**Comment by russell-taylor** [comment]
Sorry about that.  Just pushed a commit to master that should fix this.
