### ISSUE TITLE
re-use existing OpenGL context

### ISSUE THREAD

**Issue by rhegner** [sensics/OSVR-RenderManager#127]
I'm integrating OSVR in an existing application. I will have to render the same objects on the screen and for the headset. I'm not at all an expert with OpenGL. But I think this should be possible with shared contexts?

Now the existing application creates a context for the output to the window. And it looks like OpenDisplay also creates a new context.

Is it possible to make OpenDisplay re-using the existing context instead of creating a new one? Or is using shared contexts the wrong way to go anyway for what I'm trying to achieve?

**Comment by russell-taylor** [comment]
https://github.com/sensics/OSVR-RenderManager/blob/master/examples/RenderManagerOpenGLSharedContextExample.cpp has an example for doing this.  As it stands, it creates one window and then provides whatever window creation is needed for the HMD using a shared context.

Note that we just recently changed the way shared contexts in OpenGL work.  Before, we set a flag telling whether the context should be shared or not.  Now, we provide a mechanism for the application to generate the windows and contexts to be used for rendering.  This is a bit more of a heavy-weight process, but it was put in place to also enable non-SDL contexts to be created (Steffen Kiess provided a pull requests that lets you use Qt windows).

Re-open this if it is not solving your issue, or if it doesn't work for you when you try it.

**Comment by rhegner** [comment]
Thanks for your help with this and also with my other issues! 
I noticed that the code-base I'm using is quite old (0.6.41). This is the latest version I found on the OSVR webpage. 
Where can I get newer builds? Do you by any chance provide nightly builds?
Of course it would be great if I could build everything by myself. But it looks like this is not possible since not everything required to build the project is available as open source.

**Comment by russell-taylor** [comment]
The SDK download on http://osvr.github.io/using/ has the continuous-integration builds for RenderManager along with Core and other things.  It does not have all of the shortcuts for the demo programs, but it should have everything you need to develop.  If it does not, file another issue because we want to make sure it does.

**Comment by rpavlik** [comment]
Note also that the versions for render manager and core are not the same:
core is up in the 0.6.11xxs, render manager is 0.6.43.yy atm, and that's
OK. The SDK installer will always have the latest.

On Thu, Jun 30, 2016, 12:41 PM Russell Taylor <notifications@github.com>
wrote:

> The SDK download on http://osvr.github.io/using/ has the
> continuous-integration builds for RenderManager along with Core and other
> things. It does not have all of the shortcuts for the demo programs, but it
> should have everything you need to develop. If it does not, file another
> issue because we want to make sure it does.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/sensics/OSVR-RenderManager/issues/127#issuecomment-229733261>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AADuyV0FGqtyvCh5rChtyquNwvc4zzCdks5qQ_9GgaJpZM4JCPge>
> .
>
-- 
Ryan A. Pavlik, Ph.D.
CTO - OSVR Platform
Sensics, Inc.
www.sensics.com

-- 


Latest news and blog posts (subscribe here 
<http://sensics.com/subscribe-to-our-mailing-list/> to get weekly updates):

July 5: VRguy podcast: Matt Peckham, video game critic for TIME 
<http://sensics.com/vrguy-podcast-episode-17-matt-peckham-video-game-critic-for-time/>

June 29: VRguy podcast: Tim Ruse, CEO of Zero Latency, on free-roam VR 
<http://sensics.com/vrguy-podcast-episode-16-tim-ruse-ceo-of-zero-latency-on-free-roam-vr/>
June 22: The three (and a half) configurations of eye trackers 
<http://sensics.com/the-three-and-a-half-configurations-of-eye-trackers/>

**Comment by rhegner** [comment]
Ok I'm again working on this and now I'm stuck somewhere else.

In my final application I will be using the present API so I started my experiment based on `RenderManagerOpenGLPresentExample`. Next I wanted to create a window using SDL which slowly changes its color, exactly like in `RenderManagerOpenGLSharedContextExample`. So I initialize the window (which works fine) and then in the main loop I added 

    static GLfloat bg = 0;
    SDL_GL_MakeCurrent(myWindow, myGLContext);
    glViewport(static_cast<GLint>(0),
        static_cast<GLint>(0),
        static_cast<GLint>(300),
        static_cast<GLint>(100));
    glClearColor(bg, bg, bg, 1.0f);
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
    SDL_GL_SwapWindow(myWindow);
    bg += 0.003f;
    if (bg > 1) { bg = 0; }

after the call to `PresentRenderBuffers`.

Result:
The additional window works as expected but the cube in the headset is not being updated. Do I need to make some additional call in the main loop before I render the content for the headset, to make sure that the context is set correctly? How would I do that?

**Comment by russell-taylor** [comment]
This was a bit tricky, because the frame buffer has to be kept track of and because you need to define the textures in the right context.  There is a new sample app at https://github.com/sensics/OSVR-RenderManager/blob/master/examples/RenderManagerOpenGLSharedContextPresentExample.cpp that shows how to share contexts in present mode.
