### ISSUE TITLE
Bug in RenderManagerImpl.h

### ISSUE THREAD

**Issue by rhegner** [sensics/OSVR-RenderManager#128]
`osvrRenderManagerGetRenderInfoImpl` returns an error when `renderInfoIndex > ri.size()`, but it should return an error if `renderInfoIndex >= ri.size()`

**Comment by russell-taylor** [comment]
Good catch!  Fixed in commit acff3263a9a71fb327da88ecd6bca640ebd0f6b8 in master branch.
