### ISSUE TITLE
Access violation when using C interface to register render buffers

### ISSUE THREAD

**Issue by rhegner** [sensics/OSVR-RenderManager#129]
I'm getting a "Access violation reading location 0x00000000" when trying to register render buffers with the C interface.

    OSVR_RenderManagerRegisterBufferState registerState;
    osvrRenderManagerStartRegisterRenderBuffers(&registerState);
    OSVR_RenderInfoOpenGL renderInfo;
    
    // condition (i<2) is needed to fix issue #128
    for (int i = 0; (i < 2) && (osvrRenderManagerGetRenderInfoOpenGL(renderManager, i, params, &renderInfo) == OSVR_RETURN_SUCCESS); i++)
    {
      // ...
      OSVR_RenderBufferOpenGL rb = { .dummy = 7 };
      osvrRenderManagerRegisterRenderBufferOpenGL(registerState, rb);
      // ...
    }
    osvrRenderManagerFinishRegisterRenderBuffers(renderManager, registerState, false);

The violation happens in `osvrRenderManagerFinishRegisterRenderBuffers`. But I cannot say exactly where, since I do not have the debug symbols.

Notes:

- I had to add a dummy member to the `OSVR_RenderBufferOpenGL` structure because my compiler did not accept an empty structure.
- I'm a bit irritated by the fact that in the C interface it is not required/possible to set `colorBufferName` for a render buffer

**Comment by rhegner** [comment]
Again this applies to version 0.6.41, so maybe it has already been fixed. Would be great if I could test with the latest build.

**Comment by russell-taylor** [comment]
RenderManager comes with the SDK and the latest build is available at http://osvr.github.io/using/ (we should probably remove he separate RenderManager link from that page, but it has an installer that puts useful shortcuts in place).  Looking at your other issues now.

**Comment by russell-taylor** [comment]
Jeremy and I were just talking this morning about the fact that the OpenGL C API is still partially stubbed in, rather than completely implemented.  You're getting ahead of us, well done!  We hope to have it working next week.  Very sorry that the code didn't spit out an error message rather than crashing.

**Comment by russell-taylor** [comment]
Just merged a pull request from Jeremy that finishes the OpenGL C API interface and provides an example program.  It is now required to set the colorBufferName and so forth.

This is working its way through the build process so should show up in an hour or so.  Please re-open the issue if the new version does not solve everything for you.
