### ISSUE TITLE
remove RenderManagerBackends.h or write it by hand for all platforms

### ISSUE THREAD

**Issue by JeroMiya** [sensics/OSVR-RenderManager#137]
There should be no generated header files included by client applications that are platform specific. The same set of headers for RenderManager and OSVR-Core should work for all platforms - the developer need only link against the appropriate binary.

Preferred solution is to go the route of what was done in the export headers (previously generated by cmake, now hand-written to work on all platforms). Instead of generating the header at cmake time, use the same logic the export headers do to define the flags at compile time of the client application.

**Comment by rpavlik** [comment]
This header is apparently not installed by CMake, thus not included in the built artifacts, thus breaking the build of the Unity rendering plugin ATM.

**Comment by JeroMiya** [comment]
Implemented in https://github.com/sensics/OSVR-RenderManager/pull/138

**Comment by russell-taylor** [comment]
Handled in a recent pull request.
