### ISSUE TITLE
Replace #ifdef and such for _WIN32 with

### ISSUE THREAD

**Issue by russell-taylor** [sensics/OSVR-RenderManager#140]
#include <osvr/Util/PlatformConfig.h>
#if defined(OSVR_WINDOWS)

**Comment by rpavlik** [comment]
Actually, let's rather not - `ifdef _WIN32` is standard and universal, while the other is a platform-dependent generated header.

**Comment by russell-taylor** [comment]
So... then why do we have the other one?  I assumed that we should be using OSVR-defined things within OSVR.  Glad to switch things back to _WIN32.

**Comment by godbyk** [comment]
Question: Should we modify the standard `OSVR_{platform}` macros to operate at compile-time instead of configure-time?

**Comment by rpavlik** [comment]
I don't remember why you added that header, Kevin. Perhaps git can tell us.

If we keep it a shipped, public header, it's preferable to be compile time rather than configure time, yes.

**Comment by russell-taylor** [comment]
Put them back to _WIN32 in dcc4f222b6413379b18d8f6361d92792aff45e1d
