### ISSUE TITLE
Question: SDL with RenderManager

### ISSUE THREAD

**Issue by gauravbhatt89** [sensics/OSVR-RenderManager#169]
Hello, I am new to all of this and was going through the examples in the RenderManager code. I can see all examples are direct to display. I am able to run these on my HTC Vive. But I want to create a window and see the drawing on window as well as the HMD. Does doing this with RenderManager is a good idea or should I use the clientKit.

**Comment by russell-taylor** [comment]
See issue https://github.com/sensics/OSVR-RenderManager/issues/170 for a bit of discussion on this topic.  The problem with doing that in RenderManager as things stand now is that there is not a way to tell it to use a different display configuration than the one provided by the server.  We've talked for awhile about adding this kind of preview window to RenderManager itself, described by the config file.
