### ISSUE TITLE
linux installation problem

### ISSUE THREAD

**Issue by nemanja-rakicevic** [sensics/OSVR-RenderManager#186]
Hello,
I am using Ubuntu 14.04 LTS, and trying to make my HTC Vive work. 
I've already installed: SDL, OpenGL, OpenVR and (i guess) Steam and SteamVR, but SteamVR doesn't seem to work, and I cannot connect to the HMD. Basically, when I try to run "vrcmd" example, I get an error that the headset is not recognized.

I am giving OSVR a shot, so I installed OSVR-Core and OSVR-Vive successfully, but I have problems with SteamVR-OSVR (not sure if I need it) and also OSVR-RenderManager.

I've cloned the repository:
git clone https://github.com/sensics/OSVR-RenderManager.git

but when I try with CMake, I get:
```
~/OSVR/OSVR-RenderManager/build$ cmake ..
-- Git reports version 00_06_43-381-g1600a70
-- Could NOT find nvapi (missing:  NVAPI_LIBRARY NVAPI_INCLUDE_DIR NDA) 
-- Could NOT find liquidvr (missing:  LIQUIDVR_INCLUDE_DIR) 
-- Git's description of the current revision indicates this is a prerelease of 07.34: version_07.33-310-ge75e92c

-- Configuring the VRPN suite version 07.34.0~prerelease-git-07.33-310-ge75e92c using the CMake-based build system

-- NOTE: You have VRPN_USE_LOCAL_HIDAPI enabled, but VRPN_USE_HID disabled: HIDAPI will only be built if you enable HID support for VRPN
--  - NVIDIA direct support: disabled (need NVAPI and NVIDIA NDA submodule)
--  - AMD direct support: disabled (need LIQUIDVR and AMD NDA submodule)
--  - Intel direct support: disabled (need Intel NDA submodule)
--  - OpenGL support: enabled
-- Configuring done
-- Generating done
-- Build files have been written to: /home/petar/OSVR/OSVR-RenderManager/build
```

Could anyone please help me with this?

Thank you.

**Comment by russell-taylor** [comment]
That means CMake worked and you're ready to run "make" to get executables.  Only those with access to the NDA repositories can build the NVIDIA, AMD, and Intel libraries (basically only at Sensics for now).
