### ISSUE TITLE
Crash when passing NULL GraphicsLibrary structure to D3D C API

### ISSUE THREAD

**Issue by russell-taylor** [sensics/OSVR-RenderManager#19]
If you pass in a NULL GraphicsLibrary structure, we have a report of this crashing in D3D from mdutton3 on the OSVR/OSVR-Core Gitter channel.

**Comment by russell-taylor** [comment]
See https://gist.github.com/mdutton3/09918c41dcd06ea22615 for code to make it crash.

**Comment by mdutton3** [comment]
The (possibly invalid) callstack looks like:
4) osvrRenderManagerRegisterRenderBufferD3D11()
3) osvr::renderkit::RenderManagerNVidiaD3D11::GetTimingInfo()
2) OSVRDisplayConfiguration::print()
1) OSVR_Init()

**Comment by mdutton3** [comment]
I get the same hang/crash when I populate the GraphicsLibrary structure with a valid device+context.

**Comment by russell-taylor** [comment]
Here is a complete example program that exhibits the behavior:

#include <osvr/RenderKit/RenderManagerC.h>
#include <osvr/ClientKit/ContextC.h>
#include <osvr/RenderKit/RenderManagerD3D11C.h>

#include <stdio.h>

static OSVR_ClientContext s_context;
static OSVR_RenderManager s_renderManager;
static OSVR_RenderManagerD3D11 s_renderManagerD3D11;
static OSVR_GraphicsLibraryD3D11 s_graphicsLibrary;

void OSVR_Init()
{
  // Get an OSVR client context to use to access the devices that we need.
  uint32_t flags = 0;
  s_context = osvrClientInit("com.example.app", flags);
  s_graphicsLibrary.device = NULL;
  s_graphicsLibrary.context = NULL;
  OSVR_ReturnCode retCode = osvrCreateRenderManagerD3D11( s_context, "Direct3D11",
    s_graphicsLibrary, &s_renderManager, &s_renderManagerD3D11 );
  fprintf( stderr, "OSVR ret code = %u\n", (unsigned int) retCode );

  retCode = osvrRenderManagerGetDoingOkay( s_renderManager );
  fprintf( stderr, "OSVR ret code = %u\n", (unsigned int) retCode );

  OSVR_OpenResultsD3D11 openResults;
  fprintf( stderr, "About to open\n" ); fflush(stderr);
  osvrRenderManagerOpenDisplayD3D11( s_renderManagerD3D11, &openResults );
  fprintf( stderr, "Opened.\n" ); fflush(stderr);
  fprintf( stderr, "Open results: %u\t%p\n", openResults.status, (void*)openResults.library.device );
}

int main()
{
  OSVR_Init();
}

**Comment by mdutton3** [comment]
When using the C API, `ConvertGraphicsLibrary `will instantiate a `GraphicsLibraryD3D11 `struct even when provided with `NULL`s for device and context. Then in other places, it looks to be assumed that if `m_graphicsLibrary.D3D11` is not `NULL` then the device and context are valid. See `RenderManagerD3D11Base::RenderManagerD3D11Base`

**Comment by russell-taylor** [comment]
This is fixed in branch https://github.com/sensics/OSVR-RenderManager/tree/fixing-d3d-issues which is about to be pulled into master.
