### ISSUE TITLE
Mac port shows black screen

### ISSUE THREAD

**Issue by russell-taylor** [sensics/OSVR-RenderManager#204]
I tried going back several commits to find out where this happened, but the mac version is showing only black screens during rendering.  Linux is still working.

**Comment by russell-taylor** [comment]
Old version from March works: e75e92c11ac7aef840a29755d33606a4f338fba4

**Comment by russell-taylor** [comment]
Version from Jun 20 does not: a9bf800351ca044c72a5e0f589a147daa7b0d52d

**Comment by russell-taylor** [comment]
Version from Jun 29 d8e6c69ea9bf48a7b5a35f8145e29f3d91b530a6 works.
Version from Jul 12 7193322c78d2f141fee569ded23a5fcca9bbe45d works.
Version from Jul 12 f1dcb9fe4ef561494c09c9d0e9e346b4839d6e3f works.
Version from Jul 14 7de2800c149ff82236b9aca0d31671b3213fa66a does not.
Version from Jul 15 ab7f96ca18824662fffb4319b78c4039076216f6 does not.

**Comment by russell-taylor** [comment]
The commit that breaks this is one that is storing and re-setting the framebuffer binding

**Comment by russell-taylor** [comment]
If we remove the code the stores and then re-sets the framebuffer binding, we get random garbage rendered to the screen and OpenGL errors.  If we leave it in, we get black and OpenGL errors after glDrawElements in PresentEye().

**Comment by godbyk** [comment]
By the way, [`git bisect`](https://git-scm.com/book/en/v2/Git-Tools-Debugging-with-Git#Binary-Search) is handy for tracking down these kinds of things. You tell it if the current commit is good or bad and it'll automatically checkout the next commit (binary search) until you find the problem commit.

**Comment by russell-taylor** [comment]
Pulling from latest master (which puts back in the VAO code) gets a black screen and a single OpenGL error at the end of OpenDisplay()

**Comment by russell-taylor** [comment]
The error message is coming from UpdateDistortionMeshesInternal()

**Comment by russell-taylor** [comment]
Okay, the error message was a red herring -- calling using the right parameter turns it back into a black screen.

**Comment by russell-taylor** [comment]
Taking out the checking and restoring of the bound frame buffer makes things work again on the mac.    Around line 1142 of RenderManagerOpenGL.cpp...

**Comment by russell-taylor** [comment]
Fixed in 03b6f9cafcfe5f9e765ca1dc5dae3fc2f24f56a5 by more careful handling of the bound frame buffers.
