### ISSUE TITLE
Newest master has broken build on Linux from a clean clone

### ISSUE THREAD

**Issue by russell-taylor** [sensics/OSVR-RenderManager#250]
If you configure once under ccmake and then generate, things work fine.
If you configure a second time, it fails due to a problem with target JsonCpp::JsonCpp.

**Comment by rpavlik** [comment]
Should be easy to fix with updated cmake modules - was going through this yesterday for VRPN and noticed they were out of date.

**Comment by russell-taylor** [comment]
Fixed as of version 833d48dcfed6bd4eef00e1f9874b7c12e8c3bc20
