### ISSUE TITLE
How to Enable Direct Mode in my HMD

### ISSUE THREAD

**Issue by dbx999** [sensics/OSVR-RenderManager#254]
I use  Application “OSVR Central”，click “Enable Direct Mode” ，OSVR HDK 1.3 enter Direct Mode is OK。
but when usb other HMD device ，is only extend mode，when I clicn “Enable Direct Mode”，No reaction。who can give me some advice

**Comment by russell-taylor** [comment]
The HMDs that are known to OSVR, and thus configured by enable/disable directmode, are listed at https://github.com/sensics/OSVR-RenderManager/blob/master/osvr/RenderKit/DirectModeVendors.h#L147

It is also possible to run either of those programs directly and give it the three-letter vendor code for a device, in which case it will try that code in addition to the ones listed here.  Note that on nVidia, a device must be listed in their driver whitelist before it can be turned into DirectMode.

**Comment by dbx999** [comment]
thanks for you help!
if I want to add My HMD device on nVidia ,I must connect to nVidia to add my devices on their whitelist?
whether I only add three-letter vendor code in "DirectModeVendors" Array is ok?

**Comment by russell-taylor** [comment]
Adding to DirectModeVendors is necessary to make this work in OSVR, but it is not sufficient to make the display work on an nVidia card.  That requires contacting nVidia directly and getting added to the white list that is built into their drivers.
