### ISSUE TITLE
Direct Mode Question

### ISSUE THREAD

**Issue by dbx999** [sensics/OSVR-RenderManager#257]
I clone the renderManager source code , find that the "EnableOSVRDirectMode" is submodule under NDA.
so,if I don't have nVidia's NDA  myself HMD device will not use Direct Mode?
and how to get nVidia's NDA?

**Comment by russell-taylor** [comment]
Sensics releases binaries linked against the NDA code at https://osvr.github.io/using/ so that you can link against and use them.  If you are developing an HMD, you will also want to see https://github.com/OSVR/OSVR-Docs/blob/master/Extending-OSVR/AddingHMD.md
