### ISSUE TITLE
Error "NVAPI call returned -180" after consecutive runs

### ISSUE THREAD

**Issue by tobi-tobsen** [sensics/OSVR-RenderManager#262]
Hi, I am getting the following error: 

> Error Rendermanager: OSVR Rendermanager Warning: got error from nvidia API: NVAPI call returned -180 (hex: ffffff4c) nvapi invalid configuration. Could not aquire display access for vendor Id 44806 for display 0. Rendermanager D3D11Opengl::OpenDisplay Cant open d3d11display

When I am getting this error right after booting the system, unplugging and replugging the HDK2 sometimes helps.

However, **consecutive starts of the application result in the aforementioned error**. This also happens with the osvr samples. 

I am using the HDK2 in direct mode on a zotac en970, windows7 x64 and Nvidia drivers 373.06.

**Comment by tobi-tobsen** [comment]
Here are the logfiles of the server and the application.
[app_2016-11-09_14-56.log.txt](https://github.com/sensics/OSVR-RenderManager/files/594121/app_2016-11-09_14-56.log.txt)
[osvr_server_2016-11-09_14-56.log.txt](https://github.com/sensics/OSVR-RenderManager/files/594122/osvr_server_2016-11-09_14-56.log.txt)

**Comment by rpavlik** [comment]
I'm assuming you're putting the HDK into direct mode (with enabledirectmode) before starting the apps.

Can you post the output of DirectModeDebugging?

**Comment by tobi-tobsen** [comment]
Yes of course. Here is what I did:

1. Set Direct Mode with enabledirectmode
1. Launched DirectModeDebugging  (Setting direct mode worked, see [directmode.log.txt](https://github.com/sensics/OSVR-RenderManager/files/599317/directmode.log.txt))
1. Launched the HighPolyOpenGL sample which fails
1. Launched DirectModeDebugging (DirectMode is no longer enabled, see [directmode_2.log.txt](https://github.com/sensics/OSVR-RenderManager/files/599318/directmode_2.log.txt)
)

**Comment by tobi-tobsen** [comment]
Update: This is also happening on a NVIDIA GeForce GTX 1070 8GB GDDR5 "VR Ready" System. Unfortunatly, I cannot get the logs of this system just now, but I strongly suspect that it is the same issue. Any idea what is causing it?

**Comment by rpavlik** [comment]
Direct mode debugging exits direct mode, so if your config is set up to be direct mode, you'll need to run the enter direct mode app again after running debugging.

Also, try the preview firmware linked in Reddit.

**Comment by tobi-tobsen** [comment]
@rpavlik Great, the firmware update postet on [reddit](www.reddit.com/r/OSVR/comments/5ei7mh/prerelease_firmware_for_hdk2_fixing_display/) worked! I can now use the HDK2 with zotac en970, windows7 x64 and Nvidia drivers 373.06 in direct mode and consecutive starts of the application and samples still work. Good job!
