### ISSUE TITLE
RenderManagerD3DCAPIExample Black screen flashes

### ISSUE THREAD

**Issue by DuFF14** [sensics/OSVR-RenderManager#276]
This example flashes a black screen every second or so. Reproducible in extended or direct mode. I haven't seen this in other examples.

**Comment by russell-taylor** [comment]
That is the expected behavior for this demo, as it shows how to use the PresentSolidColor function.  Given that this has caused at least two bug reports, perhaps we should copy this program to a new name and remove this functionality from the CAPI example so as not to confuse others.
