### ISSUE TITLE
Sharing the OpenGL context

### ISSUE THREAD

**Issue by Armada651** [sensics/OSVR-RenderManager#31]
I'm a little bit confused about how the OpenGL context should be shared with the RenderManager. I've already created an OpenGL context for my application. Will I be able to share that context with the RenderManager or should the RenderManager be responsible for creating the context?

Preferably I could share the OpenGL context with the RenderManager and still render to my own window normally.

**Comment by russell-taylor** [comment]
Right now, RenderManager always creates the OpenGL context.  That won't work with Unity and Unreal integration, so we're in the middle of figuring out how to handle this.  It has always been in the design to enable context sharing but has not yet been implemented.  With D3D, shared contexts are available.  With OpenGL, there are OS- and library-specific ways to get the context, so we're looking at maybe just asking RenderManager to keep the original context and not create a new one.

We hope to have something on this in the next few weeks.

Ideas appreciated, especially just now before we do the implementation.

**Comment by Armada651** [comment]
I don't have any other suggestions, I'm not that familiar with context sharing. For now I'll try to see if I can disable our OpenGL context.

**Comment by Armada651** [comment]
Looks like we heavily depend on our own OpenGL context handling, so I can't easily disable it. Hopefully OSVR can finish this soon, the RenderManager is definitely the way forward for OSVR.

**Comment by sradigan** [comment]
It looks like VTK does something similar with ```InitializeFromCurrentContext``` as I just found while researching how to make VTK use the RenderManager's context.

Diff of the commit that introduced it:
http://www.vtk.org/gitweb?p=VTK.git;a=commitdiff;h=2eb0792e;hp=4b7b1394d222a71090f1c0c7b3042f06587338e0

Official documentation:
http://www.vtk.org/doc/nightly/html/classvtkRenderWindow.html#a6e14295f59ec142fc1023e525e79bb86

**Comment by russell-taylor** [comment]
Thanks for the pointers!  This is on my ToDo list for early next week, unless you beat me to it with a pull request...

**Comment by Armada651** [comment]
@russell-taylor Any update on this?

**Comment by russell-taylor** [comment]
Actually... this got pushed down on the stack by looking at performance issues and than I ran out of hours on this project.  I'm currently playing catch-up on hours and this has gotten pushed down on the stack a bit, so I think you'll win the race...  I'll leave this in my email inbox and hope to squeeze it in early next week.  Sorry about the slow response.

**Comment by Armada651** [comment]
@russell-taylor Unfortunately I have a lot of other projects I need to work on, so I don't have time to make any significant contributions to the OSVR RenderManager. I will continue to work on integrating OSVR once this issue is resolved.

**Comment by russell-taylor** [comment]
@Armada651 Okay, I've got a branch and a pull request that has an example program that creates its own OpenGL context and asks RenderManager to share it.  The branch is  at https://github.com/sensics/OSVR-RenderManager/tree/opengl-sharing that hopefully will work with Unity's OpenGL path.  There is an example program showing how to ask for this.  You need to create a library like at https://github.com/sensics/OSVR-RenderManager/blob/opengl-sharing/examples/RenderManagerOpenGLShared... and then pass that library into the creaatRenderManager() call.  Let me know if you get the chance to test this and I'll close my internal issue if it works.

**Comment by russell-taylor** [comment]
This has now been pulled into the master branch. I'm going to go ahead and close the issue.  You can re-open if it is not working when you try it.

**Comment by Armada651** [comment]
@russell-taylor Sorry, haven't been able to test this yet, I will try it out as soon as I have time to work on the Dolphin Emulator again.
