### ISSUE TITLE
Profiling GPU events in Render manager

### ISSUE THREAD

**Issue by raunaqbn** [sensics/OSVR-RenderManager#312]
Currently any application (the DX Cube example) does not show the ATW packet in a profiling tool like GPU view.There is no way to measure the performance of ATW.
- Is there a way to profile the direct mode events in GPU view? Is there a flag to enable the ETW logging with the Render Manager?
- Is there a way to check when the ATW is scheduled using GPUview and how long it takes for it to process? Are there any specific symbols that are required for this?
- Are there any special techniques to verify that the ATW is working?
- Is there a way to view the Direct mode VSync event in GPU view?

**Comment by russell-taylor** [comment]
You can verify that ATW is working using a couple of approaches.  One is to run one of the RenderManager example programs that exercise it: AdjustableRenderingDelay(D3D or OpenGL) with a half-second delay and verify that the update rate is smoothed.  Another is to look for '[RenderManager]: RenderManagerD3D11ATW: Starting ATW thread' in the console output of any of the demo programs (or in the log file if logging is enabled).

Also, ATW monitors itself and logs a message (also to the console) if it misses a frame.  When it misses a frame, it reports the length of time each sub-step of rendering took to give an idea of what is going wrong.  These messages look like this:
Apr 08 07:40:50.092 info [RenderManager]: RenderManagerThread::threadFunc(): Missed 1+ frame at 18, expected interval 11.111ms but got 22.203
Apr 08 07:40:50.092 info [RenderManager]:   (PresentRenderBuffers took 7.914ms)
Apr 08 07:40:50.092 info [RenderManager]:   (FrameInit 0, WaitForSync 0.896, DisplayInit 0.002, PresentEye 0.048, DisplayFinal 0, FrameFinal 6.934)
