### ISSUE TITLE
The IPD is not configurable for OSVR

### ISSUE THREAD

**Issue by raunaqbn** [sensics/OSVR-RenderManager#313]
Hey Guys,
Is there a way to configure the IPD for the eyes in the render manager config files?
It seems like the IPD is kept fixed at 63 mm here: https://github.com/sensics/OSVR-RenderManager/blob/master/osvr/RenderKit/RenderManager.h#L330

Is there a way to configure the IPD in a JSON file? If not what is the suggested approach for adjusting the IPD?

**Comment by russell-taylor** [comment]
IPD is a per-frame value that is set to a default in https://github.com/sensics/OSVR-RenderManager/blob/master/osvr/RenderKit/RenderManager.h#L342

This can be used to adjust it over time, perhaps to calibrate to a new user.
