### ISSUE TITLE
Multi-GPU direct mode support broken during refactoring

### ISSUE THREAD

**Issue by rpavlik** [sensics/OSVR-RenderManager#33]
Commit in question is here: https://github.com/sensics/OSVR-RenderManager/commit/20e8e2445fa81faca5fa4dcede69cbe7434f8ebc

The underlying concern is that there is a bunch of processing that needs to happen (in particular, enumeration of which devices support direct mode) in subclasses that support direct mode, before we can reliably have a `IDXGIAdapter` in the code around https://github.com/sensics/OSVR-RenderManager/commit/20e8e2445fa81faca5fa4dcede69cbe7434f8ebc#diff-c1563522d9fcfcc122b7be39a675d87eR166 - because on a multigpu system, the one that Windows hands you by default might not, and probably isn't, the right one for direct mode. Thus, direct mode subclasses, who can actually find the right adapter to correspond to the display, call `setAdapter()` before calling this base class `openDisplay()`.

I agree that the class design here is a bit funky and could use refactoring, (and I am a bit surprised there wasn't a warning that you had a "conditional expression is constant") but that particular move was a regression.

**Comment by russell-taylor** [comment]
This should be fixed in the fixing-d3d-issues branch, which I plan to use to fix other issues on the D3D path and the do a pull request for.

**Comment by russell-taylor** [comment]
I think this got fixed in that pull request.  Re-open if not.
