### ISSUE TITLE
AMD sub-module no longer uses NDA s.d.k? 

### ISSUE THREAD

**Issue by adammunich** [sensics/OSVR-RenderManager#354]
Not really an "issue" per se, but, the LiquidVR SDK from AMD is no longer protected under NDA. Given that being the case, the AMD submodule might not need to be kept private anymore. 

https://github.com/GPUOpen-LibrariesAndSDKs/LiquidVR/

I had reached out to AMD about getting an NDA for contributing to the OSVR AMD source, and their response was more or less, "You don't need one".

**Comment by russell-taylor** [comment]
Thanks for pointing this out!  We're looking into it!

**Comment by rpavlik** [comment]
Sorry to say this isn't what you think it is - if they've published the "Direct2Display" part of the LiquidVR API somewhere, that would be new, but I don't see an indication that this is that (and when I most recently asked for an updated version from my AMD contact, he didn't mention anything about it going non-NDA)
