### ISSUE TITLE
Direct Mode w/ DK1 results in [NVAPI_RESOURCE_NOT_ACQUIRED] after 12 seconds of rendering

### ISSUE THREAD

**Issue by kaisparkle** [sensics/OSVR-RenderManager#367]
Hi,
I'm currently trying to get Direct Mode working with the Rift DK1 and OSVR-OpenHMD, as Extended has always felt off to me and made me feel dizzy. The D3D sample renders properly, with some strange jitter and a ~50fps framerate, but only for ~12 seconds before I receieve this error:

```
Apr 04 22:34:45.499 error [RenderManager]: OSVR RenderManager Warning: Got error from NVIDIA API: NVAPI call returned -203 (hex: ffffff35)
Apr 04 22:34:45.500 error [RenderManager]:  [NVAPI_RESOURCE_NOT_ACQUIRED]
Apr 04 22:34:45.500 error [RenderManager]: RenderManagerNVidiaD3D11::PresentFrameFinalize: Could not present surface 0 to display 0
Apr 04 22:34:45.501 error [RenderManager]: RenderManager::PresentRenderBuffers(): PresentFrameFinalize failed.
```
My RenderManager config is [here.](https://hastebin.com/iwuyugehiq.json)
With the SteamVR plugin, SteamVR exhibits the same behaviour - renders perfectly fine, but drops after around 12 seconds.
I'm using a GTX 1050 Ti.

**Comment by kaisparkle** [comment]
Weird, after rebooting and leaving my PC on all day it works...?    
Odd.

**Comment by russell-taylor** [comment]
Worrisome.  I was going to ask whether you were using the VRPN driver to read the position, because at least the DK2 will go into power-down on the display if it is not being driven from the USB port.

If the SteamVR plug-in you are talking about is the non-OSVR one, then I suspect the hardware.

**Comment by kaisparkle** [comment]
Yeah, seems to be with my system config. After consecutive power cycles of the Rift box, it'll exhibit the same behaviour. Letting a sample crash then power cycling seems to fix it.
