### ISSUE TITLE
Direct mode doesn't work with mobile Nvidia GPUs

### ISSUE THREAD

**Issue by demonixis** [sensics/OSVR-RenderManager#376]
Hello,
Direct mode feature doesn't work with Nvidia mobile GPUs using driver version upper to 367 series. It's a [known issue](https://github.com/OSVR/OSVR-Docs/blob/master/Troubleshooting/RenderManager.md) reported in the documentation. 

Oculus, OpenVR as well as Windows MR have working direct mode with those GPU with latest drivers. Maybe drivers have changed or have a new API to make it work again?

**Comment by russell-taylor** [comment]
Are you trying to report the fact that it is still not working and ask for it to be fixed, or are you asking whether it may already be working on later drivers?

The DK2 and OSVR HDK are working on my laptop with a 2080 and a built-in Intel card, so unless you're having trouble on another machine I think I'll just remove the compatibility warning.

**Comment by demonixis** [comment]
Hello,
Well I can't get dirtect mode to work on my laptop (which has an intel + nvidia 1060 6G). I searched on the docs and it's indicated that since drivers 367 it doens't work anymore, unless you disable the other GPU. I don't want to report the issue because it's an already known issue. However, I ask if it can be fixed because direct mode works with other VR vendors.

I tried to use the latest OSVR AIO installer + update the OSVR core with the latest version available [from here] and it's still not working.

I use a HDK 1.3 which has the latest firmware (2.0). So the question is, if it's not a bug on my side, do you think it can be fixed? Or if it's already fixed, how can I fix my computer to have direct mode ;)

Thanks.

**Comment by russell-taylor** [comment]
I'll check next week when I get home and see if my HDK 2.0 works on the latest driver on a 1080 card in a laptop with the current OSVR source build against the latest nVidia VRWorks API.

**Comment by demonixis** [comment]
Thanks. Is RenderManager logs something is direct mode fails to start?

**Comment by russell-taylor** [comment]
Yes  Posting the program's output to the command line could help debug the issue.  There is also a DirectModeDebugging program that tries to make sure that the device can be recognized as a DirectMode-compatible device.

**Comment by demonixis** [comment]
I'll post all log tomorrown, thanks!

**Comment by russell-taylor** [comment]
I was able to get the HDK 2.0 running in DirectMode on an Alienware laptop with a GeForce 1080 and the built-in Intel graphics using the HDMI port.  This was running with osvrRenderManager.dll that was built against the latest VRWorks SDK.

I was also able to get it to run using a DLL made back in 2016.

It looks like the newer drivers are making things work for the HDK2.0.  It may be that the version 1.3 HDK did not have HDCP support, which I think is why nVidia removed support from these devices.  In that case, I don't know that there is anything we can do about it at this point.

**Comment by demonixis** [comment]
Ok thanks
