### ISSUE TITLE
Persistence / Motion Blur

### ISSUE THREAD

**Issue by ChristophLGDV** [sensics/OSVR-RenderManager#38]
Sorry for this rather unrelated question but I would like some second opinion on the rendering experience.

I have tried the various examples and stepped through the persistence modes and notice that there is (still) some heavy motion blur.

It "feels" that the low persistence rendering is even worse, since the contrast are weaker and the eye seems to do its perception magic even better.

So, is there a solution to the blur or are 60Hz just insufficient?

**Comment by russell-taylor** [comment]
This question won't get attention from the right people in this repository.  I recommend opening an issue either in the OSVR-General project (https://github.com/OSVR/OSVR-General/issues) or in the Gitter discussion (https://gitter.im/OSVR/OSVR-General)
