### ISSUE TITLE
LiquidVR detection returns true if DLL is installed

### ISSUE THREAD

**Issue by d235j** [sensics/OSVR-RenderManager#48]
The current implementation of LiquidVR Direct Mode looks for the amdlvr32 DLL and if it can successfully open the DLL, it returns true for AMD. This causes issues if the DLL is present but there is no AMD card, or one that does not support LiquidVR.

Ideally this could be fixed at the same time as #33.

**Comment by rpavlik** [comment]
For those no longer with an AMD card in their system, it's possible this tool might be a workaround: http://support.amd.com/en-us/kb-articles/Pages/AMD-Clean-Uninstall-Utility.aspx - haven't tested it, though.

**Comment by demonixis** [comment]
This tool will not remove AMD dlls, you've to do it by yourself. I had the issue few month ago when switched from an AMD to NVIDIA card...

**Comment by russell-taylor** [comment]
Make a workaround by trying to open nVidia cards first in commit 932b7dd5d613105e1dc6fec0e4b83613df49d942 which should go into master later today.  We don't seem to have a false positive on nVidia drivers being installed.

**Comment by russell-taylor** [comment]
The DirectRender logic has been changed to try all available DirectMode interfaces, so this should now generate a warning but not stop the display from being opened correctly.
