### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by Balderick** [sensics/OSVR-RenderManager#49]
The main `getting started` git OSVR-doc page links to https://github.com/OSVR/OSVR-Docs/blob/master/installing/RenderManager.md after clicking the "Install and test RenderManager" hyper link gives 404.

~~I think this is the page it should link to: https://github.com/sensics/OSVR-RenderManager~~

**Comment by russell-taylor** [comment]
This link has been removed.  Thanks!
