### ISSUE TITLE
cmake unnecessarily copies osvr libraries

### ISSUE THREAD

**Issue by ChristophHaag** [sensics/OSVR-RenderManager#67]
This line is the cause: https://github.com/sensics/OSVR-RenderManager/blob/db34892405935933437db309b23c22aa2e670509/CMakeLists.txt#L296

With `make install`, the libraries
libosvrClient.so.0.6
libosvrClientKit.so.0.6
libosvrCommon.so.0.6
libosvrUtil.so.0.6
will be copied back to the install directory (/usr/lib), where they most likely already are.

I've removed the line and it still builds successfully. Is this necessary on other platforms?

**Comment by russell-taylor** [comment]
This lets us get a working install when the library is built from source and there is not an installed OSVR Core library.  This is how I build, and other developers do the same.  Is the extra copy causing a problem?  If not, then I think it is more general to leave it in.

**Comment by ChristophHaag** [comment]
It's not really a problem, they'll just be overwritten with themselves. I just saw it when making an Archlinux AUR package for render manager: with a simple make install the package wouldn't install because those 4 libraries were already in /usr/lib. Well, it's trivial to remove them from the package when building (or to remove the line from CmakeLists.txt with sed).

**Comment by russell-taylor** [comment]
Okay, then I'll go ahead and close the issue.  Thanks for letting us know about it.

**Comment by rpavlik** [comment]
Ideally this would be enabled on Windows only, and/or be behind an `option()`, but if you can work around it in packaging, that works for me :)
