### ISSUE TITLE
Error opening Vive in DirectMode

### ISSUE THREAD

**Issue by DuFF14** [sensics/OSVR-RenderManager#73]
Getting this error when trying to open Vive in Direct Mode:

![image](https://cloud.githubusercontent.com/assets/10972018/14610148/9f44abd8-055a-11e6-9487-11c44b162f0f.png)

HTC_Vive_Pre_meshdata.json is located in the displays folder, another copy is next to osvr_server.exe, and also in C:/OSVR/
where should the meshdata file live?

**Comment by russell-taylor** [comment]
We're moving away from the client-side file specification.  It was put in as a quick work-around for a particular vendor until the long-json patch is put into the server transport.  Safest is to give the file name as an absolute path like C:/OSVR/HTC.json and put the data there.

**Comment by rpavlik** [comment]
Did you follow the instructions for ViveDIsplayExtractor? That will build a custom mesh data file for your particular headset, as well as a custom display descriptor file for your headset that also has a hard-coded absolute path.
