### ISSUE TITLE
Detect low VRAM situations and log them somehow

### ISSUE THREAD

**Issue by rpavlik** [sensics/OSVR-RenderManager#80]
The best example of this that I know of is trying to run Showdown on a machine with a 1GB GPU and numBuffers = 2. That app is high on its GPU memory usage, more than its processing usage. When you turn numBuffers = 2, presumably some buffer allocation at some level of the stack (quite possibly not RenderManager) fails, and you get a flickering/twitching display. Drop it back down to numBuffers = 1, and the total system gpu mem usage pulls back under the amount onboard the GPU, and it's smooth(er) again.

![showdown-mem-usage](https://cloud.githubusercontent.com/assets/61129/14892694/a4191f66-0d31-11e6-848d-0dabf2f9ad73.png)

I know that shipping a numBuffers = 2 config file is impending and better for the majority of users that probably have a better graphics card with more than 1 GB of VRAM, but some feedback would be useful for those lower-end cards, especially since they can run plenty of things fast if they aren't running what's essentially an art and rendering tech demo (Showdown).

**Comment by russell-taylor** [comment]
This seems a little beyond the kind of profiling that a library should do, and more like something you'd want to run the GPU perf to find out.
