### ISSUE TITLE
Visual Studio Build Errors

### ISSUE THREAD

**Issue by beeryt** [sensics/OSVR-RenderManager#94]
I'm trying to build OSVR_RenderManager and I've successfully created the solution using CMake, however when I build I get [several errors](http://pastebin.com/ivvT2uj5) about being unable to find `'..\bin\Debug\osvrRenderManagerd.lib'`

**Comment by russell-taylor** [comment]
Up near the top, there are errors finding SDL.h, which is causing it not to be able to build the library, which is causing it not to be able to link to the library.  We tried to configure CMake so it would not try and build things it didn't have, but it looks like the missing SDL2 library snuck through.  You'll need to build and install SDL2 and then point CMake at it to get things compiling.

**Comment by beeryt** [comment]
Ok I installed the [SDL2 development library](https://www.libsdl.org/download-2.0.php) and pointed CMake at it. I should note a [few missing items I noticed](http://pastebin.com/inUK7bg2). When building I still get [build errors](http://pastebin.com/x9iPBt6a).

**Comment by russell-taylor** [comment]
It looks like JsonCPP has been compiled Release and you're trying to compile the RenderManager with debug.  You can try compiling in Release or RelWithDebInfo.  Or you can recompile JsonCpp and install it in Debug.

**Comment by beeryt** [comment]
Yep. That fixed it!

**Comment by a409197988** [comment]
Thanks a lot,It worked.
